name: Build dts

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-dtb:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gccnone
        run: |
          git clone https://github.com/Firefly-rk-linux/prebuilts-gcc-linux-x86-aarch64-gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.git
            mv prebuilts-gcc-linux-x86-aarch64-gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu gcc-arm-gnu

      - name: Install dependencies (dtc device-tree-compiler)
        run: |
          sudo apt update
          sudo apt install -y device-tree-compiler \
          make gcc libssl-dev liblz4-tool \
          live-build bison flex fakeroot cmake

      - name: Compile11
        run: |
          make ARCH=arm64 CROSS_COMPILE=./gcc-arm-gnu/bin/aarch64-none-linux-gnu- mrproper
          make ARCH=arm64 rockchip_linux_defconfig O=outccc

      - name: Compile22
        run: |
          make ARCH=arm64 O=outccc CROSS_COMPILE=./gcc-arm-gnu/bin/aarch64-none-linux-gnu- prepare

      - name: Compile33
        run: |
          make ARCH=arm64 O=outccc \
          CROSS_COMPILE=./gcc-arm-gnu/bin/aarch64-none-linux-gnu- \
          $(find ./arch/arm64/boot/dts/rockchip/ -name "*35*.dts" | sed 's|arch/arm64/boot/dts/||;s|\.dts$|\.dtb|') \
          -j$(nproc)

      # 上传编译好的 dtb 供下载
      - name: Upload DTB artifact
        uses: actions/upload-artifact@v4
        with:
          name: dtbssbb
          path: |
            outccc/
         #   **/*.dtb
         #   **/*.dts
          retention-days: 2

      # 这里改成你自己的 dts 路径和输出文件名
      - name: Compile RK3568 dts
        run: |
          dtc -I dtb -O dts -W no-unit_address_vs_reg \
          -s -H both -@ \
          ./arch/arm64/boot/dts/rockchip/rk3568-evb4-lp3-v10.dtb \
          -o rk3568-evb4-lp3-v10--.dts

      # 上传编译好的 dtb 供下载
      - name: Upload DTB artifact
        uses: actions/upload-artifact@v4
        with:
          name: evb4dtbss
          path: |
            rk3568-evb4-lp3-v10--.dts
          retention-days: 2
